### ISSUE TITLE
Example for processing preupload

### ISSUE THREAD

**Issue by grantbi** [balderdashy/skipper-s3#20]
Would it be possible to provide an example of how to modify the file pre-upload in the upstream?
IE. Generate a resized image before uploading.

or could this API also be used for uploading a file stored from the .tmp directory?

**Comment by jurajpetrik** [comment]
+1

**Comment by luofan189** [comment]
+1

**Comment by luofan189** [comment]
I tried to use gm to resize the image before uploading to s3, but due to limited knowledge of streams, I had no luck so far. An example of the preprocessing will be very helpful!

**Comment by jurajpetrik** [comment]
The way I do it now is use skipper-disk, resize the image locally and upload that one. That's a very bad way to do it though

**Comment by sgress454** [comment]
The short answer is, there's no way to do this with the S3 adapter as-is.  

To do it, need to add some code to the [receiver](https://github.com/balderdashy/skipper-s3/blob/master/index.js#L181-L276) that accepts a [Transform stream](https://nodejs.org/api/stream.html#stream_class_stream_transform) as an option, pipes `__newFile` through the transformer, and then sends the transformed stream to S3 [instead of __newFile](https://github.com/balderdashy/skipper-s3/blob/master/index.js#L224).  

Of course, a better solution would be to tackle this at the [Skipper](https://github.com/balderdashy/skipper) level, by allowing you to pass in an array of Transform streams that should operate on any files before they hit the receivers at all.  If anyone's up for it, this would be a great addition to the project.
